version: "3.5"
services:
  backend:
    build:
      context: ./backend
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    networks:
      - docker-net
  webcam:
    build:
      context: ./webcam
    environment:
      - PORT=3002
    ports:
      - "3002:3002"
    networks:
      - docker-net
