# Generated by Django 4.0.1 on 2022-02-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=45)),
                ('user_email', models.CharField(max_length=45)),
                ('user_password', models.CharField(max_length=45)),
                ('user_address', models.CharField(max_length=45)),
                ('user_type', models.CharField(max_length=45)),
            ],
        ),
    ]
